export const paragraph1="The plot begins with a fight between Wazim and S.I. Reji Mathew. Wazim narrates about how they reached the current situation. The reason for the current fight was another fight that happened 2 years back during Wazim's wedding with popular vlogger Fathima Beepaathu Beevi. Due to the fight, Wazim becomes an infamous internet celebrity with the title Manavaalan. Two years before, Wazim meet his friends - Jamshi, Vikas and Rajesh. The friendship between Jamshi and Wazim begun due to a fight in a Masjid that happened due to Wazim putting his shoes on Jamshi's shoes. Later they both, along with Wazim's old friend Sathar, leave for a football match, which is interrupted by the fight between Vikas and Rajesh. As the trio joins in the fight, the friendship circle expanded."
export const paragraph2=" Few days later, Wazim's father runs a cinema theatre. At the theatre,Wazim meets Beepaathu, where they became friends, and Beepathu invites Wazim for a shop inauguration, but couldn't attend due of the fightswith Jamshi, Vikas, and Rajesh. Later the friends meet Omega Babu to settle the score for Jamshi, but they couldn't settle the score as Wazim slapped Siyad, with whom Wazim has another score to settle.Later, Sathar brings Beepathu to Wazim's theatre to watch a film, but Siyad and his gang intervene, where another fight erupts, leading to the theatre's destruction."
export const paragraph4=" Two years later, Wazim is an internet celebrity, who returns back home and learns that Beepathu is getting engaged to another person. Meanwhile, Reji meets Wazim to settle the score of the wedding fight. A hand-to-hand combat ensues, where Reji defeats Wazim. Now a happy man, Reji decides to reunite Wazim and Beepathu, where they arrive for Dubai to meet her. When Wazim and gang arrives to meet Beepathu. Omega babu arrives, where another fight erupts between Wazim's gang and Omega Babu to settle score for Jamshi."
export const paragraph3="    Eventually, Wazim was sent to Dubai. Two years later, Wazim returnshome and meets Beepathu again. They fall in love and decide to get married. Meanwhile, Wazim's friends gets involved in another fight with Reji's gang, which leads to severe wounds for Wazim's gang.Reji tries to patch up things but leads t anoher fight during Wazim'swedding. This fight breaks Wazim's marriage, and Wazim is sent back to Dubai again. "
export const reviews=
[
    {name:'fais',
    text:'goood movie ,wow aswesome'},
    {name:'nadeer',
    text:'i watched three times!! fantastic experience'},
    {name:'isku',
    text:'editing poli.. vere level padam'}
]